services:
  - type: web
    name: streamlit-isl-gesture
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
